[package]

name = "gfx"
version = "0.1.0"
authors = [
    "Brendan Zabarauskas <bjzaba@yahoo.com.au>",
    "Corey Richardson <corey@octayn.net>",
    "kvark",
]

[[lib]]
name = "gfx"
path = "src/gfx/lib.rs"

[dependencies.gfx_macros]
path = "src/gfx_macros"

[dependencies.device]
path = "src/device/"

[dependencies.render]
path = "src/render/"
