[package]

name = "example-draw-list"
version = "0.1.0"
authors = [
]

[[bin]]
name = "draw-list"
path = "main.rs"

[dependencies.gfx]
path = "../../../"

[dependencies.gl_init_platform]
path = "../../gl_init_platform"
